version: '3.9'

services:
  database:
    image: mysql:5.7
    container_name: bet_api-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bet_api-mysql
    volumes:
      - mysqldata:/data/mysql

  app:
    build: .
    container_name: bet_api
    restart: always
    ports:
      - 3333:3333
      - 9229:9229 #debug
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  mysqldata:
    driver: local
